name: Build Cross-Browser Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for ${{ matrix.browser }}
      run: npm run build:production:${{ matrix.browser }}
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: rolltogether-${{ matrix.browser }}
        path: build${{ matrix.browser == 'firefox' && '-firefox' || '' }}/
    
  package:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build both browsers
      run: |
        npm run build:production:chrome
        npm run build:production:firefox
    
    - name: Package extensions
      run: npm run package
    
    - name: Upload Chrome package
      uses: actions/upload-artifact@v3
      with:
        name: rolltogether-chrome-zip
        path: rolltogether-chrome.zip
    
    - name: Upload Firefox package
      uses: actions/upload-artifact@v3
      with:
        name: rolltogether-firefox-zip
        path: rolltogether-firefox.zip
